/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CompileResult {
  code: string
  map: string
  declarations: string
  errors: Array<string>
}
/** Compile a `.ck` source string into a JS module targeting the `cooked` runtime. */
export declare function compile(source: string, filename?: string | undefined | null): CompileResult
