/**
 * File-based routing support: scans `.ck` files under `src/routes`, feeds the route
 * table to the app through the `virtual:cooked-routes` module, and generates
 * a declaration file that registers every path (and its params) with
 * `cooked/router` for type-safe `Link`/`navigate`.
 */

import { readdirSync } from "node:fs";
import { join, relative } from "node:path";

export interface RouteEntry {
  /** Route pattern, e.g. `/posts/$id`. */
  pattern: string;
  /** Absolute path of the `.ck` route file. */
  file: string;
  /** Absolute paths of `__layout.ck` files wrapping it, outermost first. */
  layouts: string[];
}

const LAYOUT_FILE = "__layout.ck";

/** Scan a routes directory into route entries. Returns [] if the dir is absent. */
export function scanRoutes(routesDir: string): RouteEntry[] {
  const entries: RouteEntry[] = [];
  walk(routesDir, routesDir, [], entries);
  return entries.sort((a, b) => a.pattern.localeCompare(b.pattern));
}

function walk(routesDir: string, dir: string, layouts: string[], out: RouteEntry[]): void {
  let items;
  try {
    items = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }

  const layoutFile = items.find((i) => i.isFile() && i.name === LAYOUT_FILE);
  const nextLayouts = layoutFile ? [...layouts, join(dir, LAYOUT_FILE)] : layouts;

  for (const item of items) {
    const full = join(dir, item.name);
    if (item.isDirectory()) {
      walk(routesDir, full, nextLayouts, out);
      continue;
    }
    if (!item.isFile() || !item.name.endsWith(".ck") || item.name === LAYOUT_FILE) continue;

    const relDir = relative(routesDir, dir).split("\\").join("/");
    const name = item.name.slice(0, -".ck".length);
    const segments = relDir === "" ? [] : relDir.split("/");
    if (name !== "index") segments.push(name);
    out.push({
      pattern: "/" + segments.join("/"),
      file: full,
      layouts: nextLayouts,
    });
  }
}

/** JS source of the `virtual:cooked-routes` module. */
export function routesModule(entries: RouteEntry[]): string {
  const lines = entries.map((entry) => {
    const layouts = entry.layouts.map((l) => `() => import(${JSON.stringify(l)})`).join(", ");
    return [
      "  {",
      `    path: ${JSON.stringify(entry.pattern)},`,
      `    load: () => import(${JSON.stringify(entry.file)}),`,
      `    layouts: [${layouts}],`,
      "  },",
    ].join("\n");
  });
  return `export const routes = [\n${lines.join("\n")}\n];\n`;
}

function paramsType(pattern: string): string {
  const params = pattern
    .split("/")
    .filter(Boolean)
    .flatMap((part) => {
      if (part === "$") return ["splat"];
      if (part.startsWith("$")) return [part.slice(1)];
      return [];
    });
  if (params.length === 0) return "Record<string, never>";
  return `{ ${params.map((p) => `${JSON.stringify(p)}: string`).join("; ")} }`;
}

/** Declaration file registering all route paths with `cooked/router`. */
export function routesDeclaration(entries: RouteEntry[]): string {
  const routes = entries
    .map((e) => `      ${JSON.stringify(e.pattern)}: { params: ${paramsType(e.pattern)} };`)
    .join("\n");
  return [
    "// Generated by vite-plugin-cooked — do not edit.",
    'import "cooked/router";',
    "",
    'declare module "cooked/router" {',
    "  interface Register {",
    "    routes: {",
    routes,
    "    };",
    "  }",
    "}",
    "",
  ].join("\n");
}
